---
version: 1.2.1
configurations:
  debug:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '9.1'
  release:
    overrides:
      IPHONEOS_DEPLOYMENT_TARGET: '9.1'
targets:
  FrameworkExample:
    sources: FrameworkExample
    platform: ios
    type: ":framework"
    configuration:
      INFOPLIST_FILE: FrameworkExample/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.FrameworkExample
      IPHONEOS_DEPLOYMENT_TARGET: '9.1'
  FrameworkExampleTests:
    sources: FrameworkExampleTests
    references:
    - FrameworkExample
    platform: ios
    type: ":bundle.unit-test"
    configuration:
      INFOPLIST_FILE: FrameworkExampleTests/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: uk.lyptt.FrameworkExampleTests
      IPHONEOS_DEPLOYMENT_TARGET: '9.1'
      FRAMEWORK_SEARCH_PATHS:
      - $(inherited)
      - $(BUILT_PRODUCTS_DIR)